version: "3.3"
services:
    mysql-standalone:
      image: mysql:8.0
      volumes:
        - ./dbdata:/var/lib/mysql
      restart: always
      environment:
        - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      ports:
        - "3308:3306"
    springboot-docker-container:
      image: springboot-docker-container
      ports:
        - "8080:8080"
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/studentManagerDB?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
        SPRING_DATASOURCE_USERNAME: "root"
        SPRING_DATASOURCE_PASSWORD: "${ROOT_PASSWORD}"
      build:
        context: "./"
        dockerfile: "dockerfile"
      depends_on:
        - mysql-standalone
